config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :new_task
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # Needed to instantiate the form_with
  end

  def create
    @task = Task.new(task_params)
    @task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul class="index">
<% @tasks.each do |task| %>
 <li class="index"><%=link_to task.title, task_path(task)%></li>
<% end %>
</ul>
<div class="test">
 <h2><%=link_to "créer une nouvelle tache", new_task_path%></h2>
</div>

app/views/tasks/new.html.erb
<h1>Creez votre nouvelle tache</h1>
<ul class ="parentform">
<%= form_with model: @task do |f| %>
  <li class ="childlabel"><%= f.label :title %></li>
  <li class ="childform"><%= f.text_field :title %></li>
  <li class ="childlabel"><%= f.label :details %></li>
  <li class ="childform"><%= f.text_field :details %></li>
  <li class ="childlabel"><%= f.label :completed %></li>
  <li class ="childform"><%= f.check_box :completed %></li>
  <li class ="childbtn"><%= f.submit %></li>
<% end %>
</ul>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<ul class="index">
<li class="index"><%= @task.details %></li>
<li class="index"><%= @task.completed %></li>
</ul>
<div class="test">
<h2><%=link_to "go back", tasks_path%></h2>
</div>
<div class="test">
<h2><%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%></h2>
</div>